# Generated by Django 2.2.6 on 2019-10-30 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='documento',
            field=models.BigIntegerField(null=True, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='El documento introducido debe ser de 8 dígitos', regex='[0-9]{8}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='domicilio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nacimiento',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.RegexValidator(message='Introduzca un numero de teléfono válido, con la forma "+011-123456", o sea: "+", característica provincial, "-" (guión), y por último número de teléfono. En caso de ser celular, omita el "15".', regex='[0-9]{2,4}-[0-9]{6}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'paciente'), (2, 'recepcionista'), (3, 'medico'), (4, 'administrador')], null=True),
        ),
    ]
