# Generated by Django 2.2 on 2019-11-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Masculino'), (2, 'Femenino')]),
        ),
    ]
