# Generated by Django 2.2.6 on 2019-10-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0002_auto_20191030_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='documento',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='cuil',
            field=models.BigIntegerField(unique=True),
        ),
    ]
