# Generated by Django 2.2.6 on 2019-11-01 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0003_auto_20191031_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='obra_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_informacion.ObraSocial'),
        ),
    ]
