# Generated by Django 2.2.7 on 2019-11-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0004_auto_20191101_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nacimiento',
            field=models.DateField(null=True),
        ),
    ]
