# Generated by Django 2.2 on 2019-11-08 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0004_auto_20191101_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('is_recepcionist', 'User has a recepcionist role'),)},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'permissions': (('is_medic', 'User has a medic role'),)},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'permissions': (('is_patient', 'User has a pacient role'),)},
        ),
    ]
