# Generated by Django 2.2.7 on 2019-11-19 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0005_auto_20191119_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('es_recepcionista', 'Usuario tiene rol de recepcionista'),)},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'permissions': (('es_medico', 'Usuario tiene rol de medico'),)},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'permissions': (('es_paciente', 'Usuario tiene rol de paciente'),)},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
    ]
