# Generated by Django 2.2 on 2019-11-14 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0005_auto_20191108_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
    ]
