# Generated by Django 2.2.7 on 2019-11-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0006_auto_20191119_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Masculino'), (2, 'Femenino')]),
        ),
    ]
