# Generated by Django 2.2.5 on 2019-10-08 12:49

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'paciente'), (2, 'recepcionista'), (3, 'medico'), (4, 'administrador')])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('documento', models.BigIntegerField(unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='El documento introducido debe ser de 8 dígitos', regex='[0-9]{8}$')])),
                ('domicilio', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.BigIntegerField(validators=[django.core.validators.RegexValidator(message='Introduzca un numero de teléfono válido, con la forma "+011-123456", o sea: "+", característica provincial, "-" (guión), y por último número de teléfono. En caso de ser celular, omita el "15".', regex='[0-9]{2,4}-[0-9]{6}$')])),
                ('nacimiento', models.DateTimeField()),
                ('registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_conexion', models.DateTimeField()),
                ('genero', models.PositiveSmallIntegerField(choices=[(1, 'masculino'), (2, 'femenino')])),
                ('penalizado', models.BooleanField(default=False)),
                ('fecha_penalizacion', models.DateTimeField()),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.ObraSocial')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendiente', models.BooleanField(default=True)),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'pendiente'), (2, 'aceptado'), (3, 'cancelado'), (4, 'sobreturno')])),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico_que_atiende', to='turnos.Paciente')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_a_atender', to='turnos.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Sobreturno',
            fields=[
                ('turno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='turnos.Turno')),
                ('prioridad', models.PositiveSmallIntegerField()),
            ],
            bases=('turnos.turno',),
        ),
        migrations.CreateModel(
            name='TurnoCancelado',
            fields=[
                ('turno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='turnos.Turno')),
                ('fecha_cancelado', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('turnos.turno',),
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('documento', models.BigIntegerField(unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='El documento introducido debe ser de 8 dígitos', regex='[0-9]{8}$')])),
                ('domicilio', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.BigIntegerField(validators=[django.core.validators.RegexValidator(message='Introduzca un numero de teléfono válido, con la forma "+011-123456", o sea: "+", característica provincial, "-" (guión), y por último número de teléfono. En caso de ser celular, omita el "15".', regex='[0-9]{2,4}-[0-9]{6}$')])),
                ('nacimiento', models.DateTimeField()),
                ('registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_conexion', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('documento', models.BigIntegerField(unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='El documento introducido debe ser de 8 dígitos', regex='[0-9]{8}$')])),
                ('domicilio', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.BigIntegerField(validators=[django.core.validators.RegexValidator(message='Introduzca un numero de teléfono válido, con la forma "+011-123456", o sea: "+", característica provincial, "-" (guión), y por último número de teléfono. En caso de ser celular, omita el "15".', regex='[0-9]{2,4}-[0-9]{6}$')])),
                ('nacimiento', models.DateTimeField()),
                ('registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_conexion', models.DateTimeField()),
                ('cuil', models.BigIntegerField(unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='La constancia de CUIL introducida debe ser de formato "XX-XXXXXXXX-X".', regex='[0-9]{2}-[0-9]{8}-[0-9]$')])),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.Especialidad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('documento', models.BigIntegerField(unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='El documento introducido debe ser de 8 dígitos', regex='[0-9]{8}$')])),
                ('domicilio', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.BigIntegerField(validators=[django.core.validators.RegexValidator(message='Introduzca un numero de teléfono válido, con la forma "+011-123456", o sea: "+", característica provincial, "-" (guión), y por último número de teléfono. En caso de ser celular, omita el "15".', regex='[0-9]{2,4}-[0-9]{6}$')])),
                ('nacimiento', models.DateTimeField()),
                ('registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_conexion', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
