# Generated by Django 2.2 on 2020-02-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_app', '0002_auto_20200212_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='medicos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='pacientes',
            field=models.IntegerField(default=0),
        ),
    ]
