# Generated by Django 2.2 on 2020-02-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_app', '0003_auto_20200222_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='obrasocial',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
