# Generated by Django 2.2 on 2020-03-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_app', '0005_auto_20200327_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horariolaboral',
            old_name='dia_laboral',
            new_name='dias',
        ),
    ]
