# Generated by Django 2.2 on 2020-03-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos_app', '0006_auto_20200327_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariolaboral',
            name='intervalo',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
