# Generated by Django 2.2 on 2019-11-20 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaLaboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
            ],
        ),
        migrations.CreateModel(
            name='HorarioLaboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('sobreturnos', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'disponible'), (2, 'reservado'), (3, 'confirmado'), (4, 'atendido'), (5, 'cancelado')])),
                ('fecha', models.DateTimeField()),
                ('es_sobreturno', models.BooleanField(default=False)),
                ('prioridad', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TurnoAtendido',
            fields=[
                ('turno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_turnos.Turno')),
                ('diagnostico', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TurnoCancelado',
            fields=[
                ('turno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_turnos.Turno')),
                ('fecha_cancelado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
