# Generated by Django 2.2.6 on 2019-10-30 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'disponible'), (2, 'pendiente'), (3, 'aceptado'), (4, 'cancelado'), (5, 'atendido')])),
                ('fecha', models.DateTimeField()),
                ('is_sobreturno', models.BooleanField(default=False)),
                ('prioridad', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TurnoAtendido',
            fields=[
                ('turno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_turnos.Turno')),
                ('diagnostico', models.TextField()),
            ],
            bases=('app_turnos.turno',),
        ),
        migrations.CreateModel(
            name='TurnoCancelado',
            fields=[
                ('turno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_turnos.Turno')),
                ('fecha_cancelado', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('app_turnos.turno',),
        ),
    ]
