# Generated by Django 2.2 on 2019-11-20 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_turnos', '0001_initial'),
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_usuarios.Medico'),
        ),
        migrations.AddField(
            model_name='turno',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_usuarios.Paciente'),
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='dia_laboral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_turnos.DiaLaboral'),
        ),
        migrations.AddField(
            model_name='dialaboral',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_usuarios.Medico'),
        ),
    ]
