# Generated by Django 2.2.7 on 2019-11-14 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_turnos', '0002_auto_20191030_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_usuarios.Paciente'),
        ),
    ]
