# Generated by Django 2.2.7 on 2019-11-19 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0005_auto_20191119_0041'),
        ('app_turnos', '0003_auto_20191114_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaLaboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_usuarios.Medico')),
            ],
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='is_sobreturno',
            new_name='es_sobreturno',
        ),
        migrations.RemoveField(
            model_name='turnoatendido',
            name='turno_ptr',
        ),
        migrations.RemoveField(
            model_name='turnocancelado',
            name='turno_ptr',
        ),
        migrations.AddField(
            model_name='turnoatendido',
            name='turno',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_turnos.Turno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnocancelado',
            name='turno',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_turnos.Turno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'disponible'), (2, 'reservado'), (3, 'confirmado'), (4, 'atendido'), (5, 'cancelado')]),
        ),
        migrations.CreateModel(
            name='HorarioLaboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sobreturnos', models.BooleanField(default=False)),
                ('dia_laboral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_turnos.DiaLaboral')),
            ],
        ),
    ]
