# Generated by Django 2.2.7 on 2019-11-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_turnos', '0004_auto_20191119_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariolaboral',
            name='hora_fin',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horariolaboral',
            name='hora_inicio',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
