# Generated by Django 2.2.7 on 2019-11-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_turnos', '0005_auto_20191119_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Disponible'), (2, 'Reservado'), (3, 'Confirmado'), (4, 'Atendido'), (5, 'Cancelado')]),
        ),
    ]
